import {
	MdDashboard,
	MdFlashOn,
	MdVisibility,
	MdSchool,
	MdExplore,
	MdAdd,
	MdCheckCircle,
	MdBook,
	MdLibraryBooks,
	MdBookmark,
	MdHighlight,
	MdCloudUpload,
	MdPerson,
	MdAssessment,
	MdQuiz,
	MdFlag,
	MdTune,
} from "react-icons/md";
import { SidebarConfig } from "./Sidebar";

const menuItems: SidebarConfig = {
	logo: {
		src: "/brain.png",
		alt: "HireMind Logo",
		title: "HireMind",
	},
	showProfile: true,
	showLogout: true,
	menuItems: [
		{
			id: "dashboard",
			name: "Dashboard",
			icon: <MdDashboard />,
			type: "heading",
			children: [
				{
					id: "overview",
					name: "Overview",
					icon: <MdVisibility />,
					href: "/dashboard",
					type: "link",
				},
				{
					id: "quick-actions",
					name: "Quick Actions",
					icon: <MdFlashOn />,
					href: "/dashboard/quick-actions",
					type: "link",
				},
			],
		},
		{
			id: "learning-paths",
			name: "Learning Paths",
			icon: <MdSchool />,
			type: "heading",
			children: [
				{
					id: "my-paths",
					name: "My Paths",
					icon: <MdPerson />,
					href: "/dashboard/my-paths",
					type: "link",
				},
				{
					id: "browse-paths",
					name: "Browse All Paths",
					icon: <MdExplore />,
					href: "/dashboard/browse-paths",
					type: "link",
				},
				{
					id: "create-path",
					name: "Create Custom Path",
					icon: <MdAdd />,
					href: "/dashboard/create-path",
					type: "link",
				},
				{
					id: "completed-paths",
					name: "Completed Paths",
					icon: <MdCheckCircle />,
					href: "/dashboard/completed-paths",
					type: "link",
					badge: "New",
				},
			],
		},
		{
			id: "resources",
			name: "Resources",
			icon: <MdBook />,
			type: "heading",
			children: [
				{
					id: "my-library",
					name: "My Library",
					icon: <MdLibraryBooks />,
					href: "/dashboard/library",
					type: "link",
				},
				{
					id: "bookmarks",
					name: "Bookmarks",
					icon: <MdBookmark />,
					href: "/dashboard/bookmarks",
					type: "link",
				},
				{
					id: "notes-highlights",
					name: "Notes & Highlights",
					icon: <MdHighlight />,
					href: "/dashboard/notes",
					type: "link",
				},
				{
					id: "browse-resources",
					name: "Browse Resources",
					icon: <MdExplore />,
					href: "/dashboard/browse-resources",
					type: "link",
				},
				{
					id: "upload-content",
					name: "Upload Content",
					icon: <MdCloudUpload />,
					href: "/dashboard/upload",
					type: "link",
				},
			],
		},
		{
			id: "profile-assessment",
			name: "Profile & Assessment",
			icon: <MdPerson />,
			type: "heading",
			children: [
				{
					id: "personal-profile",
					name: "Personal Profile",
					icon: <MdPerson />,
					href: "/dashboard/profile",
					type: "link",
				},
				{
					id: "skills-assessment",
					name: "Skills Assessment",
					icon: <MdAssessment />,
					href: "/dashboard/skills-assessment",
					type: "link",
				},
				{
					id: "interest-survey",
					name: "Interest Survey",
					icon: <MdQuiz />,
					href: "/dashboard/interest-survey",
					type: "link",
				},
				{
					id: "career-goals",
					name: "Career Goals",
					icon: <MdFlag />,
					href: "/dashboard/career-goals",
					type: "link",
				},
				{
					id: "learning-preferences",
					name: "Learning Preferences",
					icon: <MdTune />,
					href: "/dashboard/learning-preferences",
					type: "link",
				},
			],
		},
	],
};

export default menuItems;
