#!/bin/sh

echo "Running lint..."
npm run lint
LINT_STATUS=$?

echo "Running format..."
npm run format
FORMAT_STATUS=$?

if [ $LINT_STATUS -ne 0 ] || [ $FORMAT_STATUS -ne 0 ]; then
    echo "Lint or format failed. Commit aborted."
    exit 1
fi

echo "Lint and format completed successfully."

exit 0